version: "3.9"
services:
  checkit_frontend:
    image: "nginx:latest"
    container_name: "frontend_checkit"
    ports:
    - "80:8080"
    volumes:
    - ./website:/www
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
