version: "3.9"
services:
  checkit_frontend:
    image: "checkit_frontend:latest"
    container_name: "checkit_frontend"
    ports:
    - "80:8080"
    # environment:
    #   - CHECKIT_BACKEND_PROTOCOL="http"
    #   - CHECKIT_BACKEND_PORT="5000"
    #   - CHECKIT_BACKEND_ADDRESS="10.0.2.11"
    restart: always
