version: "3.9"
services:
  checkit_frontend:
    image: "checkit_frontend:latest"
    container_name: "checkit_frontend"
    ports:
    - "80:8080"
    environment:
      - CHECKIT_BACKEND_URL="http://10.0.2.11"
    restart: always
