#version: "3.9"
services:
  checkit_backend:
    image: checkit_backend
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
    volumes:
      - ./checkit.db:/data/checkit.db
    container_name: "checkit_backend"
    restart: always
