on:
  push:
    branches:
    - release/*
  workflow_dispatch:
    
name: Bump dotnet Version

jobs:
  bump_dotnet:
    name: "Bump dotnet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: DotNet Bump Versions
        # You may pin to the exact commit or the version.
        # uses: SiqiLu/dotnet-bump-version@8ce81f63c5b13eefd2440a3d480efea3b77cdcdd
        uses: SiqiLu/dotnet-bump-version@2.0.0
        with:
          # Version files to bump version. You can use Glob pattern string (like "**/*.csproj") or Glob patterns array json string (like "["**/*.csproj", "v1.version", "**/*.version.json", "!v2.version.json"]"). Patterns supported by Globby are supported. Leading ! changes the meaning of an include pattern to exclude.
          version_files: backend/*.csrpoj # optional, default is **/*.csproj
          # Control which part of the version to be bumped. The input must have four parts(split by "."). Example: "1.0.0.0": Bump the major part of the version.  2.3.4.5 => 3.0.0.0 "0.1.0.0": Bump the minor part of the version.  2.3.4.5 => 2.4.0.0 "0.0.1.0": Bump the patch part of the version.  2.3.4.5 => 2.3.5.0 "0.0.0.1": Bump the minor part of the version.  2.3.4.5 => 2.3.4.6 "1.0.1.0": Bump the major and the patch part of the version.  2.3.4.5 => 3.0.5.0 "1.1.1.1": Bump all the parts of the version.  2.3.4.5 => 3.4.5.6 
          version_mask: 0.0.1.0 # optional, default is 0.0.1.0
          # Overwrite the bumped version. The input must have four parts(split by "."). Use this input option to overwrite the version or part of the version. If you want to modified all versions in the version files to a specifed version number, you should use this input option. If you do not want overwrite the version or any part of the version, you should just ignore this input option. Example: "*.*.*.*" does not overwrite ant part of the version. "1.*.*.*" overwrite the major part with number 1. "*.*.*.Alpha" overwrite the build part with string "Alpha". "*.*.*.github.run_number" overwrite the build part with "github.run_number".
          # The github token to push changes.
          github_token: ${{ secrets.GITHUB_TOKEN }}
