name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend
    - name: Build
      run: dotnet build --no-restore
      working-directory: backend
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm ci
      working-directory: frontend

    - run: npm run build --if-present
      working-directory: frontend
      env:
        CI: false
    
    - name: Build the Docker image
      working-directory: backend
      run: docker build . --file Dockerfile --tag checkit_frontend:$(date +%s)
    - name: Build the Docker image
      working-directory: frontend
      run: docker build . --file Dockerfile --tag checkit_backend:$(date +%s)
